### ISSUE TITLE
no such file to load -- will_paginate/view_helpers/action_view (LoadError)

### ISSUE THREAD

**Issue by qichunren** [fzxu/maricms#1]
<pre>
caojinhuamatoMacBook-Pro:maricms caojinhua$ bundle install
Fetching https://github.com/arkxu/mongoid-tree.git
remote: Counting objects: 1014, done.
remote: Compressing objects: 100% (513/513), done.
remote: Total 1014 (delta 436), reused 809 (delta 346)
Receiving objects: 100% (1014/1014), 158.10 KiB | 15 KiB/s, done.
Resolving deltas: 100% (436/436), done.
Fetching https://github.com/arkxu/liquid.git
remote: Counting objects: 1046, done.
remote: Compressing objects: 100% (459/459), done.
remote: Total 1046 (delta 687), reused 861 (delta 559)
Receiving objects: 100% (1046/1046), 207.81 KiB | 34 KiB/s, done.
Resolving deltas: 100% (687/687), done.
Fetching source index for http://rubygems.org/
Using rake (0.9.2) 
Using abstract (1.0.0) 
Using activesupport (3.0.7) 
Using builder (2.1.2) 
Using i18n (0.5.0) 
Using activemodel (3.0.7) 
Using erubis (2.6.6) 
Using rack (1.2.3) 
Using rack-mount (0.6.14) 
Using rack-test (0.5.7) 
Using tzinfo (0.3.27) 
Using actionpack (3.0.7) 
Using mime-types (1.16) 
Using polyglot (0.3.1) 
Using treetop (1.4.9) 
Using mail (2.2.19) 
Using actionmailer (3.0.7) 
Using arel (2.0.10) 
Using activerecord (3.0.7) 
Using activeresource (3.0.7) 
Installing bcrypt-ruby (2.1.4) with native extensions 
Using bson (1.3.1) 
Using bson_ext (1.3.1) 
Using bundler (1.0.13) 
Installing carrierwave (0.5.4) 
Installing orm_adapter (0.0.5) 
Installing warden (1.0.4) 
Installing devise (1.3.4) 
Using diff-lcs (1.1.2) 
Installing http_accept_language (1.0.1) 
Using thor (0.14.6) 
Using railties (3.0.7) 
Installing jquery-rails (1.0.9) 
Installing will_paginate (2.3.15) 
Using liquid (2.2.2) from https://github.com/arkxu/liquid.git (at master) 
Using mongo (1.3.1) 
Using mongoid (2.0.2) 
Using mongoid-tree (0.6.0) from https://github.com/arkxu/mongoid-tree.git (at master) 
Installing mongoid_order (0.0.4) 
Using rails (3.0.7) 
Using rmagick (2.13.1) 
Installing rspec-core (2.6.4) 
Installing rspec-expectations (2.6.0) 
Installing rspec-mocks (2.6.0) 
Installing rspec (2.6.0) 
Installing rspec-rails (2.6.1) 
Installing themes_for_rails (0.4.2) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
caojinhuamatoMacBook-Pro:maricms caojinhua$ rails s
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require': no such file to load -- will_paginate/view_helpers/action_view (LoadError)
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `block in require'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/bundler/gems/liquid-42b11abe0f48/lib/liquid.rb:71:in `<top (required)>'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/runtime.rb:68:in `require'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/runtime.rb:66:in `each'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/runtime.rb:66:in `block in require'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/runtime.rb:55:in `each'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler/runtime.rb:55:in `require'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/bundler-1.0.13/lib/bundler.rb:120:in `require'
    from /Users/caojinhua/code/github/maricms/config/application.rb:12:in `<top (required)>'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/commands.rb:28:in `require'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/commands.rb:28:in `block in <top (required)>'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/commands.rb:27:in `tap'
    from /Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/commands.rb:27:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
caojinhuamatoMacBook-Pro:maricms caojinhua$
</pre>

**Comment by qichunren** [comment]
rvm ruby 1.9.2

**Comment by fzxu** [comment]
yep. i can reproduce it. will fix it asap.

**Comment by fzxu** [comment]
ok. could you pull the latest master and try to update the liquid by:

bundle update liquid

**Comment by qichunren** [comment]
Now command: rails s is ok.

**Comment by fzxu** [comment]
cool. there is no doc for it now. so, hard to use :)

close it.
