### ISSUE TITLE
uninitialized constant PageMeta when rake db:seed

### ISSUE THREAD

**Issue by qichunren** [fzxu/maricms#2]
<pre>
caojinhuamatoMacBook-Pro:maricms caojinhua$ bundle exec rake db:seed --trace
** Invoke db:seed (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:seed
rake aborted!
uninitialized constant PageMeta
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.8/lib/active_support/inflector/methods.rb:124:in `block in constantize'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.8/lib/active_support/inflector/methods.rb:123:in `each'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.8/lib/active_support/inflector/methods.rb:123:in `constantize'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.8/lib/active_support/core_ext/string/inflections.rb:43:in `constantize'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/relations/metadata.rb:294:in `klass'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/relations/builders/embedded/many.rb:24:in `block (2 levels) in build'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/relations/builders/embedded/many.rb:23:in `tap'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/relations/builders/embedded/many.rb:23:in `block in build'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/relations/builders/embedded/many.rb:22:in `each'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/relations/builders/embedded/many.rb:22:in `inject'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/relations/builders/embedded/many.rb:22:in `build'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/relations/accessors.rb:59:in `create_relation'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/relations/accessors.rb:26:in `build'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/relations/accessors.rb:166:in `block (2 levels) in setter'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/attributes/processing.rb:138:in `block in process_relations'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/attributes/processing.rb:133:in `each_pair'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/attributes/processing.rb:133:in `process_relations'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/attributes/processing.rb:121:in `process_pending'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/attributes/processing.rb:28:in `process'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/document.rb:130:in `initialize'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/persistence.rb:168:in `new'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/persistence.rb:168:in `create'
/Users/caojinhua/code/github/maricms/db/seeds.rb:8:in `<top (required)>'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/railties/database.rake:15:in `block (2 levels) in <top (required)>'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:205:in `block in execute'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/Users/caojinhua/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:90:in `block (2 levels) in top_level'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:90:in `block in top_level'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:62:in `block in run'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.9.2/bin/rake:32:in `<top (required)>'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/bin/rake:19:in `load'
/Users/caojinhua/.rvm/gems/ruby-1.9.2-p180/bin/rake:19:in `<main>'
Tasks: TOP => db:seed
caojinhuamatoMacBook-Pro:maricms caojinhua$
</pre>

I found in app/models/page.rb:
embeds_many :page_metas

but I can't find PageMeta model.

**Comment by fzxu** [comment]
hm... that old seed... changed to create a default admin user then :)
